<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="example">
  <xacro:include filename="$(find sensor_description)/urdf/vlp16.urdf.xacro"/>
  <xacro:property name="camera_height" value="0.1767" />
  <xacro:property name="camera_diameter" value="0.1055" />
  <xacro:property name="camera_mass" value="1.128" />
  <material name="blue">
    <color rgba="0 0.4 0.8 1" />
  </material>

  <!-- Base Footprint -->
  <link name="camera_foot" />

  <!-- Base Link -->
  <joint name="footprint" type="fixed" >
    <parent link="camera_foot" />
    <child link="occam" />
    <origin xyz="0 0 ${camera_height / 2}" rpy="0 0 0" />
  </joint>

  <link name="occam" >
    <visual>
      <geometry>
	<cylinder length="${camera_height}" radius="${camera_diameter / 2}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <!-- <collision> -->
    <!--   <geometry> -->
    <!--     <cylinder length="${camera_height}" radius="${camera_diameter / 2}"/> -->
    <!--   </geometry> -->
    <!-- </collision> -->
    <!-- <inertial> -->
    <!--   <origin xyz="0 0 0"/> -->
    <!--   <mass value="${camera_mass}"/> -->
    <!-- </inertial> -->
  </link>

  <link name="image0" />

  <joint name="camera_inside_joint" type="fixed">
    <parent link="camera_foot" />
    <child link ="image0" />
    <origin xyz="${camera_diameter / 2} 0 ${(camera_height / 2) + 0.06}" rpy="0 0 0" />
  </joint>

</robot>
