<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="example">
  <xacro:include filename="$(find sensor_description)/urdf/vlp16.urdf.xacro"/>
  <xacro:property name="camera_height" value="0.1767" />
  <xacro:property name="camera_diameter" value="0.1055" />
  <xacro:property name="camera_mass" value="1.128" />
  <!-- <material name="gray"> -->
  <!--   <color rgba="0.4 0.4 0.4 1"/> -->
  <!-- </material> -->

  <!-- <material name="dark_gray"> -->
  <!--   <color rgba="0.2 0.2 0.2 1"/> -->
  <!-- </material> -->

  <material name="blue">
    <color rgba="0 0.4 0.8 1" />
  </material>

  <!-- Base Footprint -->
  <link name="camera_foot" />

  <!-- Base Link -->
  <joint name="footprint" type="fixed" >
    <parent link="camera_foot" />
    <child link="camera_link" />
    <origin xyz="0 0 ${camera_height / 2}" rpy="0 0 0" />
  </joint>

  <link name="camera_link" >
    <visual>
      <geometry>
	<cylinder length="${camera_height}" radius="${camera_diameter / 2}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <!-- <collision> -->
    <!--   <geometry> -->
    <!--     <box size="0.15 0.15 0.4" /> -->
    <!--   </geometry> -->
    <!-- </collision> -->
    <!-- <inertial> -->
    <!--   <origin xyz="0 0 0"/> -->
    <!--   <mass value="10"/> -->
    <!--   <inertia ixx="3.0" ixy="0.0" ixz="0.0" -->
    <!--            iyy="3.0" iyz="0.0" -->
    <!--            izz="3.0" /> -->
    <!-- </inertial> -->
    <!-- <visual> -->
    <!--   <geometry> -->
    <!--     <cylinder length="${camera_height}" radius="${camera_radius}" /> -->
    <!--   </geometry> -->
    <!--   <material name="gray"/> -->
    <!-- </visual> -->
    <!-- <collision> -->
    <!--   <geometry> -->
    <!--     <cylinder length="${camera_height}" radius="${camera_radius}"/> -->
    <!--   </geometry> -->
    <!-- </collision> -->
    <!-- <inertial> -->
    <!--   <origin xyz="0 0 0"/> -->
    <!--   <mass value="${camera_mass}"/> -->
    <!-- </inertial> -->
  </link>

  <link name="image0" />

  <joint name="camera_inside_joint" type="fixed">
    <parent link="camera_foot" />
    <child link ="image0" />
    <origin xyz="${camera_diameter / 2} 0 ${(camera_height / 2) + 0.06}" rpy="0 0 0" />
  </joint>



  <VLP-16 parent="camera_link" name="velodyne">
    <origin xyz="0 0 ${camera_height / 2}" rpy="0 0 0" />
  </VLP-16>


</robot>
