<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="example">
  <xacro:include filename="$(find sensor_description)/urdf/vlp16.urdf.xacro"/>
  <xacro:include filename="$(find sensor_description)/urdf/occam.urdf.xacro"/>
  <VLP-16 parent="occam" name="velodyne">
    <origin xyz="0 0 ${camera_height / 2}" rpy="0 0 0" />
  </VLP-16>

</robot>
